# filepath: ./k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-echo
  namespace: mcp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-echo
  template:
    metadata:
      labels:
        app: mcp-echo
    spec:
      containers:
        - name: mcp-echo
          image: ACR_LOGIN_SERVER_PLACEHOLDER/mcp-echo:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: MCP_SERVER_NAME
              value: "mcp-echo"
            - name: LOG_LEVEL
              value: "info"
            - name: PORT
              value: "8080"            # health endpoint port
            # Optional MCP-related provider keys
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mcp-secrets
                  key: ANTHROPIC_API_KEY
                  optional: true
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mcp-secrets
                  key: OPENAI_API_KEY
                  optional: true
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mcp-secrets
                  key: AZURE_OPENAI_API_KEY
                  optional: true
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: mcp-secrets
                  key: AZURE_OPENAI_ENDPOINT
                  optional: true
          ports:
            - name: health
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-echo
  namespace: mcp-demo
spec:
  type: ClusterIP
  selector:
    app: mcp-echo
  ports:
    - name: health
      port: 8080
      targetPort: 8080